apiVersion: "local.storage.openshift.io/v1"
kind: "LocalVolume"
metadata:
  name: "localstorage-ocs-osd"
  namespace: "openshift-local-storage"
spec:
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: cluster.ocs.openshift.io/openshift-storage
            operator: In
            values:
              - ''
  storageClassDevices:
    - storageClassName: "localstorage-ocs-osd-sc"
      volumeMode: Block 
      devicePaths:
        - /dev/sdb
